### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Nightmare0709** [Pago-TW/pago-frontend#22]
- [x] 1.已完成的訂單出現在商品頁

![image](https://github.com/Pago-TW/report-center/assets/104414757/8eee6936-fc77-48d8-b8a4-194dc3b214d9)
![image](https://github.com/Pago-TW/report-center/assets/104414757/396b24da-ead5-4500-97a0-b5f513775b0a)

- [x] 2.編輯會員資料裡面介紹欄，儲存變更後沒有成功更改內容。

![image](https://github.com/Pago-TW/report-center/assets/104414757/9971cd92-ed0e-4acb-b23a-ce13415f5e98)
![image](https://github.com/Pago-TW/report-center/assets/104414757/866588b8-4600-417a-9b4d-e97cfa605c25)

**Comment by EnderWolf50** [comment]
1. 無須修改
2. 無法重現
