### ISSUE TITLE
[Feature] 使用者"旅途中"顯示小飛機 icon

### ISSUE THREAD

**Issue by sh1un** [Pago-TW/pago-frontend#26]
## Description
透過 Response 中的 `isTraveling` 來辨別該使用者是否旅行中，若旅行中則顯示小飛機 Icon

## Figma
![image](https://github.com/Pago-TW/pago-frontend/assets/85695943/182ceb29-fef1-4e83-ba7e-594e50d01841)

## API endpoint: 

- List Bid: [GET /orders/{{orderId}}/bids](https://pago-tw.postman.co/workspace/Pago-Team-workspace~60222008-905d-44fa-8b7b-f82306cdd897/request/24878882-caa5ab75-331c-4638-ae32-577c770db480?ctx=documentation)
- Get User Info: [GET /users/{userId}](https://pago-tw.postman.co/workspace/Pago-Team-workspace~60222008-905d-44fa-8b7b-f82306cdd897/request/24878882-e2f3c111-39b0-4788-9eec-c791ab1273f9?ctx=documentation)
- Get Me: [GET /users/me](https://pago-tw.postman.co/workspace/Pago-Team-workspace~60222008-905d-44fa-8b7b-f82306cdd897/request/24878882-a2260f6f-7922-4e73-a5cd-850a1573cd90?ctx=documentation)
- List User Review: [GET /reviews?userId={{userId}}](https://pago-tw.postman.co/workspace/Pago-Team-workspace~60222008-905d-44fa-8b7b-f82306cdd897/request/24878882-6f50aff2-8e77-46f1-bc94-77e1b1382d27?ctx=documentation)
- Get Order: [GET /orders/{{orderId}}](https://pago-tw.postman.co/workspace/Pago-Team-workspace~60222008-905d-44fa-8b7b-f82306cdd897/request/24878882-90c940a7-8f60-412f-a9cf-2bc8aa942963?ctx=documentation)

## **Additional context**
[專題例行會議 - 20230831](https://www.dropbox.com/scl/fi/p8lnbp7m6ql9s20t5jkyq/20230831.paper?rlkey=a5k768ptzpk7kz1s9wtund7hk&dl=0)

**Comment by EnderWolf50** [comment]
@sh1un This can be reviewd too
I only added the flight icon to the `BidItem` cuz I wasn't sure how wide the design team wanted to apply it

**Comment by sh1un** [comment]
> @sh1un This can be reviewd too I only added the flight icon to the `BidItem` cuz I wasn't sure how wide the design team wanted to apply it

Hi @EnderWolf50 OK 收到，UI/UX 設計他們目前也只有畫在 Bid 那邊，所以就做 Bid 就好，後續若有其他需求我再跟你說~
