### ISSUE TITLE
[Feature] 出價留言

### ISSUE THREAD

**Issue by sh1un** [Pago-TW/pago-frontend#28]
# Description
## User Story
```
角色：身為 代購者 
需求：我想要 出價時可以留言或是備註 
價值：因此我可以 告知消費者我所提供的代購服務會有哪些額外事項須注意 (7-11賣貨便、面交地點)

接受條件：
Given 代購者已經新增旅途，想要接受委託或是對其他委託者提議更好的代購費並且留言，且已經登入(1.2)
When 代購者進入委託詳情頁面(3.1.6)
AND 代購者點擊接受委託
AND 代購者看到出價頁面，並提出議價(預設即為「委託者願支付代購費」)
AND 代購者在出價頁面留言
Then 出價成功，消費者可以看到出價資訊以及留言

優先順序: 1
```

## Figma
https://www.figma.com/file/ULkgCRqrxngEVoeRzATmJx/Pago---Mockup?type=design&node-id=4222-56959&mode=design&t=WrLazrX3Gpm56Esb-0

![image](https://github.com/Pago-TW/pago-frontend/assets/85695943/04fdae0d-69d9-4ef7-86e1-3482a8a18c62)

![image](https://github.com/Pago-TW/pago-frontend/assets/85695943/e1009695-2b10-468e-9617-148a604716f3)

## API endpoint: 

- Create Bid: POST [/orders/{{orderId}}/bids](https://pago-tw.postman.co/workspace/Pago-Team-workspace~60222008-905d-44fa-8b7b-f82306cdd897/request/24878882-41bec10a-fe4b-4471-8bdb-3060c5ce43bc?active-environment=67a1dc2f-d1b8-4c52-b596-50428a91c743)

- List Bid: [/orders/{{orderId}}/bids
](https://pago-tw.postman.co/workspace/Pago-Team-workspace~60222008-905d-44fa-8b7b-f82306cdd897/request/24878882-caa5ab75-331c-4638-ae32-577c770db480?active-environment=67a1dc2f-d1b8-4c52-b596-50428a91c743)

## **Additional context**
[專題例行會議 - 20230804](https://www.dropbox.com/scl/fi/tgmkzl7iqh2l3kgxf9j0i/20230804.paper?rlkey=r09qkes7yb24nj9trfetufhrq&dl=0)

**Comment by EnderWolf50** [comment]
@sh1un i think this one got implemented at commit ea4f893

**Comment by sh1un** [comment]
@EnderWolf50 OK 收到, 那我先把這個狀態改成 "✅ Done"

**Comment by sh1un** [comment]
Hi @EnderWolf50 
這邊有一個 UI/UX Optimize 的 issue 剛剛創建好，再麻煩先完成此項我再來確認一次此 issue

https://github.com/Pago-TW/pago-frontend/issues/37
