### ISSUE TITLE
[P0][Feature] 旅途管理 - 旅途集合頁面更新

### ISSUE THREAD

**Issue by sh1un** [Pago-TW/pago-frontend#29]
# Description
## User Story
```
角色：身為 代購者 
需求：我想要 在一次發佈好我這個旅途會行經的程式
價值：因此我可以 減少發佈的次數，不會因為我經過多個城市就要重複創建多次旅途

接受條件：
Given 代購者將的旅途將行經三個以上城市 且 日期是連貫的，並已經登入(1.2)
When 代購者點擊創建旅途
AND 代購者新增旅途(出發地、目的地、抵達時間)
Then 代購者批量發佈旅途成功，進入「旅途列表」(3.2.1)
```

## Figma
https://www.figma.com/file/ULkgCRqrxngEVoeRzATmJx/Pago---Mockup?type=design&node-id=4222-56959&mode=design&t=WrLazrX3Gpm56Esb-0

![image](https://github.com/Pago-TW/pago-frontend/assets/85695943/7380710c-d0ac-4443-9880-e6599273476f)

## API endpoint: 

- List Trip Collection: [/trip-collections](https://pago-tw.postman.co/workspace/Pago-Team-workspace~60222008-905d-44fa-8b7b-f82306cdd897/request/24878882-9184cba3-99fd-4be9-8e77-e08d85911d7e?active-environment=67a1dc2f-d1b8-4c52-b596-50428a91c743)

## Suggested Solution
1. 關於時間篩選 Button 的排序功能，預設是會依照時間由新至舊修改，你可以透過 Query Param `sort` 和 `orderBy` 去控制 data 排序

## **Additional context**
- 目前有提供 `search` 參數來達成「搜尋功能」，關於搜尋功能，依照時程是否緊湊，若有餘力請再實作出來，確認有餘力可以做，會再請 UI/UX 畫出 Figma
- [專題例行會議 - 20230804](https://www.dropbox.com/scl/fi/tgmkzl7iqh2l3kgxf9j0i/20230804.paper?rlkey=r09qkes7yb24nj9trfetufhrq&dl=0)

**Comment by EnderWolf50** [comment]
* [ ] add sorting button group (just a todo to myself)

**Comment by EnderWolf50** [comment]
@sh1un implemented through commits down blow
* f49ebf7278e7bf44552c34efd769a463bdd4d6a1
* 0b676bd8956065559a5e87908d59402b92a77230
* 21dc73a6705530fa0f9dc5a01b0b13a4183ed5da
* 39a6ec9fde4134a8d9dea84fe6421aee9edf5890
* f84209359210257e54990dc7f08ed44859ab87e6
* 079eb346cff8d2f2df0725920c66eadcadbb5b28

bonus: infinite scroll
* c6c1c59be291c858d47eff51f464569d21c64208
i forgot it for several months lmao

**Comment by sh1un** [comment]
@EnderWolf50 
OK 收到!
那我一會來看一下

**Comment by sh1un** [comment]
Hi @EnderWolf50 ,
#34 這個可能要先處理然後我再來繼續看此 issue 的內容、目前新增旅途我這邊沒看到送出 API

**Comment by sh1un** [comment]
@EnderWolf50 LGTM, nice work!

![image](https://github.com/Pago-TW/pago-frontend/assets/85695943/c4cc69d6-a957-4351-a520-77747d7e684b)
