### ISSUE TITLE
[UI/UX Optimize] 點擊頭像查看會員詳情

### ISSUE THREAD

**Issue by sh1un** [Pago-TW/pago-frontend#32]
# Description
這個功能很類似 Instagram 可以點擊用戶頭像直接進到該用戶的主頁

但以下圖片情況例外，請參考下圖：

- [ img1 聊天室列表頭像不需要做這功能 ]
![image](https://github.com/Pago-TW/pago-frontend/assets/85695943/943d4f6f-af98-42fc-acef-77d274adb094)

- [ img2 通知列表頭像不需要做這功能  ]
![image](https://github.com/Pago-TW/pago-frontend/assets/85695943/a83f1269-4b59-498b-97dd-98bba51a064b)

- [ img3-1 委託詳情 - 查看會員會員詳情 Button 改成 傳送訊息 ] 
![image](https://github.com/Pago-TW/pago-frontend/assets/85695943/138090be-7afa-4bf0-a794-d9a8b7675327)

- [ img3-2 ]
![image](https://github.com/Pago-TW/pago-frontend/assets/85695943/286f5764-5042-4b44-b826-27a63d8fad26)
- [ img3-3 ]
![image](https://github.com/Pago-TW/pago-frontend/assets/85695943/8b267934-b3c3-49b0-8fa6-249419317a40)

## API endpoint: 

- Get User Info: [/users/{{userId}}](https://pago-tw.postman.co/workspace/Pago-Team-workspace~60222008-905d-44fa-8b7b-f82306cdd897/request/24878882-e2f3c111-39b0-4788-9eec-c791ab1273f9?active-environment=67a1dc2f-d1b8-4c52-b596-50428a91c743)

## **Additional context**
- [專題例行會議 - 20230831](https://www.dropbox.com/scl/fi/p8lnbp7m6ql9s20t5jkyq/20230831.paper?rlkey=a5k768ptzpk7kz1s9wtund7hk&dl=0)

**Comment by EnderWolf50** [comment]
@sh1un should this apply to the entire Pago or just few specific pages?

**Comment by sh1un** [comment]
Hi @EnderWolf50 
已修改 issue 的需求內容
多加說明哪些地方不需要 Apply 這個功能
以及其他要注意的地方
