### ISSUE TITLE
[Bug] 旅途管理 - 要新增旅途 最後按下 Button 疑似尚未送出 API

### ISSUE THREAD

**Issue by sh1un** [Pago-TW/pago-frontend#34]
# Bug Report

## Description
如標題所示，要新增旅途，最後按下 Button，尚未送出"新增旅途 API"

### Device
**OS**: Win10 home
**Browser**: Google Chrome

### Test Account
null@gmail.com
123

### Branch
**FE branch**: dev
**BE branch**: dev

### Screenshot
- [ img1 ]
![BatchCreateTrip](https://github.com/Pago-TW/pago-frontend/assets/85695943/bc669ba3-d119-4553-a798-f7b9503b74f0)

### APIs
- Batch Create Trip: [POST /trips/batch](https://pago-tw.postman.co/workspace/Pago-Team-workspace~60222008-905d-44fa-8b7b-f82306cdd897/request/24878882-421a5bf7-68c7-4a34-9fe0-706eb35e7db2?ctx=documentation)

**Comment by EnderWolf50** [comment]
@sh1un I think there's some issues at backend?
According to the image you provided, the `POST /batch` is actually successful, however, the `GET /trip-collections` is returning status code 500

**Comment by EnderWolf50** [comment]
bruh i took a screenshot but i forgot to attach it
![image](https://github.com/Pago-TW/pago-frontend/assets/14370053/7aa12ff9-7547-4f7a-80e8-8de91b1dd884)

**Comment by EnderWolf50** [comment]
@sh1un Not sure if you missed my comments or not

**Comment by EnderWolf50** [comment]
@sh1un the green circle part is returned by the batch create api isn't it?![268452615-7aa12ff9-7547-4f7a-80e8-8de91b1dd884.png](https://github.com/Pago-TW/pago-frontend/assets/14370053/b17a39cd-ab26-4396-aaf9-ae5e209bdc7a)

**Comment by sh1un** [comment]
啊啊拍謝誤會了，我自己沒注意到 batch 那個
我現在來排除一下後端問題 https://github.com/Pago-TW/pago-backend/issues/38
