### ISSUE TITLE
[Bug & UI/UX Optimize] 旅途管理、我的委託 - 未授權(登入)卻可進入須授權頁面 Bug 與 使用者體驗優化

### ISSUE THREAD

**Issue by sh1un** [Pago-TW/pago-frontend#61]
Deadline: 2023/10/27 23:59 (GMT+8)

## Description
- [x] 1. **我的委託 - 在未登入狀態，若想要進入"我的委託頁面"應讓使用者切換至"登入頁面"，而非讓其進入"我的委託頁面"**
    * [ img1-1 gif ]
![notLogged-inBugCanEvenGotoOrderList](https://github.com/Pago-TW/pago-frontend/assets/85695943/2fdb3da8-17e2-44ba-9542-bb0e9242f9ac)

- [x] 2. **旅途管理、我的委託 - 若沒有資料應顯示提示文字，例如：目前沒有途旅、目前沒有委託...等等**
    * [ img2-1 ]
![image](https://github.com/Pago-TW/pago-frontend/assets/85695943/b9f6f482-d85a-4809-bdb8-b12921601e3e)
    * [ img2-2 ]
![image](https://github.com/Pago-TW/pago-frontend/assets/85695943/eb470ee7-4b56-4e97-b58a-f172654ea363)
    * [ img2-3 Example ]
![image](https://github.com/Pago-TW/pago-frontend/assets/85695943/be2da0cc-7522-4468-858d-aa72e05d8ce3)

- [x] 3. **旅途管理、我的委託 - 在資料還在讀取時，加上 Skeleton 或是 Progress，像首頁"最新發布委託"那樣**
    * [ img3-1 ]
![image](https://github.com/Pago-TW/pago-frontend/assets/85695943/35c1bdeb-3027-4dbb-b14d-410f7210a9f2)
    * [ img3-2 ]
![image](https://github.com/Pago-TW/pago-frontend/assets/85695943/1cf22fcc-0fb4-43f7-8476-bc2c54f4daf0)
    * [ img3-3 Example ]
![image](https://github.com/Pago-TW/pago-frontend/assets/85695943/e7d9f307-62c0-4451-9b9a-66d949a11043)

**Comment by EnderWolf50** [comment]
@sh1un  2c0237399ee77583e30fa22cf20d43c6cd826705 fixed this (maybe)

**Comment by EnderWolf50** [comment]
@sh1un i forgot to open another branch :/
all should be fixed in recent commits tho
