### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Ariel1206** [Pago-TW/pago-frontend#74]
- 商品頁"排序"篩選器bug(如圖)
![marketplace bug](https://github.com/Pago-TW/report-center/assets/105278732/027fc758-90fa-4c12-8cbd-ca61a1af852f)

**Comment by EnderWolf50** [comment]
@Ariel1206 prob fixed
you can try and close the issue if it behaves as expected

**Comment by Ariel1206** [comment]
ok 已確認沒問題
然後我才發現我 issue 建錯地方 拍謝
